name: "Networking Recipe CI Build pipeline"

on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - main
      - github-actions
      
concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: build_and_test-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build_and_test:
    timeout-minutes: 100
    runs-on: ubuntu-20.04
    steps:
      - name: 'checkout p4-dpdk repo'
        uses: actions/checkout@v3
        with:
          repository: p4lang/p4-dpdk-target
          path: p4sde

      - name: 'Install dependencies'
        working-directory: ./p4sde/tools/setup
        run: |
              #sudo apt update -y 
              #sudo apt install python python3-setuptools python3-pip python3-wheel python3-cffi sudo libssl-dev -y
              #pip3 install distro
              #python3 install_dep.py
              cmake --version
              sudo apt-get purge cmake
              cmake --version || true
              sudo rm -rf /usr/local/bin/cmake || true
              sudo rm -rf ~/.local/bin/cmake || true
              cmake --version || true
              cd /tmp
              wget https://cmake.org/files/v3.20/cmake-3.20.2-linux-x86_64.sh
              chmod a+x cmake-3.20.2-Linux-x86_64.sh
              sudo mkdir -p /opt/rh/cmake
              sudo ./cmake-3.20.2-Linux-x86_64.sh --prefix=/opt/rh/cmake --skip-license
              sudo ln -s /opt/rh/cmake/bin/cmake /usr/local/bin/cmake
              cmake --version
