name: "Networking Recipe CI Build pipeline"

on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - main
      - github-actions
      
concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: build_and_test-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build_and_test:
    timeout-minutes: 100
    runs-on: ubuntu-20.04
    steps:
      - name: 'checkout p4-dpdk repo'
        uses: actions/checkout@v3
        with:
          repository: p4lang/p4-dpdk-target
          submodules: 'recursive'
          path: p4sde

      - name: 'Install dependencies'
        working-directory: ./p4sde/tools/setup
        run: |
              sudo apt update -y 
              sudo apt install python python3-setuptools python3-pip python3-wheel python3-cffi sudo libssl-dev -y
              pip3 install distro
              python3 install_dep.py
              cmake --version
              sudo apt-get purge cmake
              cmake --version || true
              sudo apt install cmake
              cmake --version
              sudo apt-get purge cmake
              sudo rm -rf ~/.local/bin/cmake
              cmake --version || true
              pip3 install cmake==3.20.2
              cmake --version
      
     
