name: "Networking Recipe CI Build pipeline"

on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - main
      - github-actions
      
concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: build_and_test-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build_and_test:
    timeout-minutes: 100
    runs-on: ubuntu-20.04
    steps:
      - name: 'checkout p4-dpdk repo'
        uses: actions/checkout@v3
        with:
          repository: p4lang/p4-dpdk-target
          submodules: 'recursive'
          path: p4sde
      
      - name: 'checkout Networking Recipe'
        uses: actions/checkout@v3
        with:
          repository: ipdk-io/networking-recipe
          ref: drop3
          submodules: 'recursive'
          path: ipdk.recipe

      - name: 'Build and Configure infrap4d dependencies'
        run: |
             cd ${GITHUB_WORKSPACE}/ipdk.recipe
             export IPDK_RECIPE=`pwd`
             cd $IPDK_RECIPE/setup
             cmake -B build -DCMAKE_INSTALL_PREFIX=$IPDK_RECIPE/deps --trace-expand --debug-output
 
      - name: 'Execute infrap4d dependencies'
        run: |
             cd ${GITHUB_WORKSPACE}/ipdk.recipe
             export IPDK_RECIPE=`pwd`
             cd $IPDK_RECIPE/setup
             cmake --build build -j1 --verbose --clean-first
