name: Linters

on:
  push:
    branches:
      - main
      - ipdk_v*
      - dev/mgaravin/*  
  pull_request:
    branches:
      - main
      - ipdk_v*
  workflow_dispatch:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: docker run -v $PWD:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest --ignore=minutes --disable=MD013 "**/*.md"

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azohra/shell-linter@v0.6.0

  clang-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install ClangFormat
        run: sudo apt-get install -y clang-format

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          clang_format: true

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: '--config ./linters/mdl_config.yml ./*.md'   
        
