name: Linters

on:
  push:
    branches:
      - main
      - ipdk_v*
      - dev/mgaravin/*  
  pull_request:
    branches:
      - main
      - ipdk_v*
  workflow_dispatch:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install ClangFormat
        run: sudo apt-get install -y clang-format

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          clang_format: true
