name: "P4SDE DPDK build and package"

on:
  workflow_dispatch:
    branches:
      - main
      - dev/mgaravin/buildtime
  push:
    branches:
      - main
      - dev/mgaravin/buildtime            
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_p4dpdk_ubuntu:
    timeout-minutes: 100
    runs-on: ubuntu-20.04
    steps:
      - name: 'Check Out p4-dpdk repo'
        uses: actions/checkout@v3
        with:
          repository: p4lang/p4-dpdk-target
          submodules: 'recursive'
          path: p4sde

      - name: 'Install dependencies'
        working-directory: ./p4sde/tools/setup
        run: |
              sudo apt update -y
              sudo apt install python python3-setuptools python3-pip python3-wheel python3-cffi sudo libssl-dev git zip libatomic1 libnl-route-3-dev curl tree -y
              pip3 install distro
              python3 install_dep.py
              cmake --version
              sudo apt-get purge cmake
              sudo rm -rf /usr/local/bin/cmake || true
              sudo rm -rf ~/.local/bin/cmake || true
              # removing cmake 3.25 and reinstalling 3.20, as build is failing with cmake 3.25
              wget https://cmake.org/files/v3.20/cmake-3.20.2-linux-x86_64.sh -O ${GITHUB_WORKSPACE}/cmake-3.20.2-linux-x86_64.sh
              chmod a+x ${GITHUB_WORKSPACE}/cmake-3.20.2-linux-x86_64.sh
              sudo mkdir -p /opt/rh/cmake
              cd ${GITHUB_WORKSPACE} && sudo sh cmake-3.20.2-linux-x86_64.sh --prefix=/opt/rh/cmake --skip-license
              sudo ln -s /opt/rh/cmake/bin/cmake /usr/local/bin/cmake
              cmake --version
          
      - name: 'Compile P4 dpdk target'
        run: |
             export SDE=${GITHUB_WORKSPACE}
             mkdir install deps
             export SDE_INSTALL=${GITHUB_WORKSPACE}/install
             cd ${GITHUB_WORKSPACE}/p4sde
             ./autogen.sh
             ./configure --prefix=$SDE_INSTALL
             make -j6
             make install
             tar -czvf p4sde_dpdk.tar.gz -C $SDE_INSTALL .
    
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: p4sde_dpdk.tar.gz
          path: ${GITHUB_WORKSPACE}/p4sde/p4sde_dpdk.tar.gz
